service: reddit-parser

provider:
  name: google
  stage: prod
  region: us-central1
  project: tribal-artifact-263821
  credentials: /Users/jorgejch/.gcloud/web-parser-service-admin-tribal-artifact-263821.json

plugins:
  - serverless-google-cloudfunctions-amazing

package:
  exclude:
    - node_modules/**
    - venv/**
    - package.json
    - package-lock.json
    - .serverless/**
    - .idea/**
    - reddit_parser_vars.json
    - utils/**
    - std_img/**

functions:
  subreddit-new-scanner:
    memorySize: 256
    timeout: 120s
    runtime: python37
    handler: scan_subreddits_new
    serviceAccount: reddit-parser-function-agent@tribal-artifact-263821.iam.gserviceaccount.com
    labels:
      service: reddit-parser
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/tribal-artifact-263821/topics/trigger_subreddits_scan
    environment:
      SUBREDDITS: MagicArena,magicTCG,mtg,sideboardmtg
      LOG_LEVEL: DEBUG
      VARS_BUCKET: web-parser-vars
      VARS_BLOB: reddit_parser_vars.json
      TO_SMS_NUMBERS: '+18052845139'
      TO_EMAILS: jorgejch@gmail.com,tashirabten85@gmail.com
      SUBMISSION_TEXT_RE: '\b\w{3}-\w{4}-\w{3}\b'
      MEGA_IMAGE_FOLDER: mtga-promo-cards
      SMS_NOTIFY_PUBSUB_TOPIC:  'projects/tribal-artifact-263821/topics/send_sms_notification'
      EMAIL_NOTIFY_PUBSUB_TOPIC: 'projects/tribal-artifact-263821/topics/send_email_notification'
      MEGA_STORAGE_PUBSUB_TOPIC: 'projects/tribal-artifact-263821/topics/save-to-mega'